### ISSUE TITLE
Legacy REST Call (dashboard)

### ISSUE THREAD

**Issue by mparizernc** [ozone-development/ozp-rest#46]
/owf/prefs/dashboard for OWF.Preferences.createOrUpdateDashboard, deleteDashboard, findDashboards, findDashboardsByType, setDefaultDashboard

**Comment by stephanieerin** [comment]
Discussed with the team and the current behavior is returning a 404 and `{error: true}` in the response. These endpoints won't be implemented (don't exist in new product) so this was deemed a suitable response.
